spring:
  datasource:
    url: jdbc:mysql://111.231.135.83:33307/mf-edu?useUnicode=true&useSSL=false&characterEncoding=utf-8&allowMultiQueries=true
    username: kimen
    password: mys@l@kimen
    driver-class-name: com.mysql.jdbc.Driver
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
server:
  port: 8082
  context-path: /mf-edu

qiniuyun:
  ak: T5XQB_CwNFrIdhVvTClo66SdRdUhGPIt6K2iFE4Y
  sk: kJKqehmTegWIXZrR9AkZ2agrV38zZJ1wQypEYwue
  bucket: mf-edu
  outline: http://img.kimen.com.cn/

redis:
  host: 192.168.0.1
  port: 6379
