spring:
  datasource:
    url: jdbc:mysql://172.16.0.13:33308/mf-edu-prod?useUnicode=true&useSSL=false&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: mys@l@yzgs
    driver-class-name: com.mysql.jdbc.Driver
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
server:
  port: 7070
  context-path: /mf-edu

qiniuyun:
  ak: T5XQB_CwNFrIdhVvTClo66SdRdUhGPIt6K2iFE4Y
  sk: kJKqehmTegWIXZrR9AkZ2agrV38zZJ1wQypEYwue
  bucket: mf-edu-prod
  outline: http://mf-prod.kimen.com.cn/
